//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valkyrie {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valkyrie.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;service&quot;: &quot;Instagram&quot;,
        ///    &quot;url&quot;: &quot;https://www.instagram.com/{}&quot;,
        ///    &quot;urlRegister&quot;: &quot;https://www.instagram.com/&quot;,
        ///    &quot;errorType&quot;: 0,
        ///    &quot;errorMsg&quot;: null
        ///  },
        ///  {
        ///    &quot;service&quot;: &quot;Twitter&quot;,
        ///    &quot;url&quot;: &quot;https://twitter.com/{}&quot;,
        ///    &quot;urlRegister&quot;: &quot;https://twitter.com/&quot;,
        ///    &quot;errorType&quot;: 0,
        ///    &quot;errorMsg&quot;: null
        ///  },
        ///  {
        ///    &quot;service&quot;: &quot;Facebook&quot;,
        ///    &quot;url&quot;: &quot;https://www.facebook.com/{}&quot;,
        ///    &quot;urlRegister&quot;: &quot;https://www.facebook.com/&quot;,
        ///    &quot;errorType&quot;: 1,
        ///    &quot;errorMsg&quot;: &quot;This page isn&amp;#039;t avail [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SocialSites {
            get {
                return ResourceManager.GetString("SocialSites", resourceCulture);
            }
        }
    }
}
